In [1]:
import numpy as np
import pandas as pd
import pickle

In [25]:
df = pd.read_csv('./survey_answer_text.csv')
df.head()

                                  text
0                 귀여운 세포를 볼 수 있어서 좋았다.
1  유미의 세포들을 매우 좋아하는데 전시회로 감상해서 너무 좋았다
2                        좋은 추억으로 남았습니다
3  오랜만에 싱그러움을 느낄 수 있어 좋았습니다. 감사합니다. :)
4                                 잘봤어요

In [26]:
len(df)

297

In [36]:
df[df['text'].str.len()<=2.0]

    text
15    감동
20    좋다
27    좋다
41     굿
56    ♥♥
61     굿
63     굿
69     굳
74     굿
75     ♥
76     ♥
82    출출
92     .
96    꿀잠
108    굳
109    굳
116   힐링
121    X
131   대박
132   ㅇㅇ
139   아잉
140   최고
156    짱
163    굿
164    짱
171    ㅇ
186   ♥♥
188    굿
189   없음
215    짱
225    굳
227    굳
228    굳
231    굿
232    ♥
244    네
246   최고
248    굳
251    ,
255    굿
262   최고
266    굳
278   꿀잼
290    .

In [34]:
df[df['text'].str.contains('ㅇㅇ|ㅇ|.|X')]

                                    text
0                   귀여운 세포를 볼 수 있어서 좋았다.
1    유미의 세포들을 매우 좋아하는데 전시회로 감상해서 너무 좋았다
2                          좋은 추억으로 남았습니다
3    오랜만에 싱그러움을 느낄 수 있어 좋았습니다. 감사합니다. :)
4                                   잘봤어요
..                                   ...
292                             좋은시간이엿어요
293                              재밌었어요\n
294                너무 즐겁고 마음이 몽ㄱ.ㄹ몽글해쟜어요
295                                 포 유미
296                              너무 좋았어용

[297 rows x 1 columns]